### ISSUE TITLE
Check "is this page useful?" email survey is broken in staging

### ISSUE THREAD

**Issue by richardTowers** [alphagov/smokey#1252]
This looks like it's an actual problem in staging:

![image](https://github.com/alphagov/smokey/assets/1696784/098a801e-f87f-4edf-ab23-3c215d7c978e)

My best guess is that it's related to this error in Sentry:

https://govuk.sentry.io/issues/4559374078/?environment=staging&project=202223&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0

> Communication with notify service failed (NotifyService::Error)
> AuthError: Invalid token: service is archived (Notifications::Client::AuthError)

That issue was first seen on 2 Feb - perhaps something changed with the API key around then?

I've had a quick look at the secret, and a look in the UI of Notify and there wasn't anything obviously wrong as far as I could see.

**Comment by ChrisBAshton** [comment]
Yes, this looks like it was my fault 😅 - apologies!

It lines up with a Notify account deletion I performed [on 2nd February](https://trello.com/c/cyw0yjuo/94-lock-down-access-to-all-of-govuks-notify-services#comment-65bd0874cf979b70f0ebce1f) (for [reasons outlined in this comment](https://trello.com/c/cyw0yjuo/94-lock-down-access-to-all-of-govuks-notify-services#comment-65b90b466003f1826de5127f)).
