### ISSUE TITLE
Sentry: Lots of scenarios fail at 10PM [Staging]

### ISSUE THREAD

**Issue by benthorner** [alphagov/smokey#956]
Examples:

| scenario | example | link |
| - | - | - |
| origin.feature: Check that the WAF is working | <img width="1049" alt="Screenshot 2022-06-28 at 16 38 03" src="https://user-images.githubusercontent.com/9029009/176221952-249d205a-da01-440b-b075-7f739b801c71.png"> | [Recent events](https://sentry.io/organizations/govuk/issues/3354640317/events/?project=6370326&query=cucumber.scenario%3A%22Check+that+the+WAF+is+working%22&statsPeriod=14d) |
| transition.feature: Check log in to transition | (similar) | [Recent events](https://sentry.io/organizations/govuk/issues/3370952578/events/?project=6370326&query=cucumber.scenario%3A%22Check+log+in+to+transition%22&statsPeriod=14d) |
| whitehall.feature: Can log in to whitehall | (similar) | [Recent events](https://sentry.io/organizations/govuk/issues/3370952579/events/?project=6370326&query=cucumber.scenario%3A%22Can+log+in+to+whitehall%22&statsPeriod=14d) |
| smartanswers.feature: Check the app is routable for a Smart Answer | (similar) | [Recent events](https://sentry.io/organizations/govuk/issues/3370952558/events/?project=6370326&query=cucumber.scenario%3A%22Check+the+app+is+routable+for+a+Smart+Answer%22&statsPeriod=14d) |
| signon.feature: Check log in to signon | (similar) | [Recent events](https://sentry.io/organizations/govuk/issues/3370952572/events/dc36482c75444075bbd5c51611824695/?project=6370326&statsPeriod=14d) |
| service_manual_frontend.feature: Check the frontend can talk to Content Store | (similar) | [Recent events](https://sentry.io/organizations/govuk/issues/3370952557/events/?project=6370326&query=cucumber.scenario%3A%22Check+the+frontend+can+talk+to+Content+Store%22&statsPeriod=14d) |
| search_api.feature: Check app is routable | (similar) | [Recent events](https://sentry.io/organizations/govuk/issues/3370952550/events/c817575f43ad44e3bfeb27fc2258efc8/?project=6370326&statsPeriod=14d) |
| travel_advice_publisher: Can log in to travel-advice-publisher | (similar) | [Recent events](https://sentry.io/organizations/govuk/issues/3370952559/events/?project=6370326&query=cucumber.scenario%3A%22Can+log+in+to+travel-advice-publisher%22&statsPeriod=14d) |

All the recent errors seem to be related to the headless Chrome browser exiting prematurely. The previous pattern I saw was that content on the pages didn't exist i.e. the page was blank. We should figure out what is causing this. For example, it could be that part of [the data sync process starts a bit earlier than we expect](https://github.com/alphagov/govuk-puppet/blob/32c1bbbb10067078c1406170666a135b4a10aaea/modules/govuk/lib/puppet/parser/functions/data_sync_times.rb#L6). 

Note that the errors are specifically happening at 10PM +/- 1 minute. It's possible the errors continue after 10PM because that's when the data sync filter kicks in and we don't care about them anyway.

Note also that not all errors happen every day, but every day there are always some errors. This is likely just due to natural variability of when individual tests run versus when the data sync filter period starts.

**Comment by ChrisBAshton** [comment]
Since https://github.com/alphagov/govuk-puppet/pull/11954, we no longer have the Smokey Loop, instead using Jenkins cron scheduler to run Smokey every ten minutes.

We've configured Jenkins to only [run the tests between 7am and 7pm](https://github.com/alphagov/govuk-puppet/pull/11954/files#diff-1d6545debf57c939cf04cd386bebe4998adce5de5bff6a55a46e4047e3ef6cbcR24), so this issue should no longer appear. Closing.
