### ISSUE TITLE
Sentry: Licensing stops working from 7PM [Integration, Staging]

### ISSUE THREAD

**Issue by benthorner** [alphagov/smokey#958]
Applies to:

| scenario | example | link |
| - | - | - |
| licensing.feature: Check licensing pages load | <img width="1038" alt="Screenshot 2022-06-28 at 16 31 23" src="https://user-images.githubusercontent.com/9029009/176219892-06b41851-cb4f-4c64-9367-45d693a12f9a.png"> | [Recent events](https://sentry.io/organizations/govuk/issues/3298791978/events/?project=6370326&query=cucumber.scenario%3A%22Check+licensing+pages+load%22&statsPeriod=14d) |
| frontend.feature: Check the frontend can talk to Licensing | <img width="1054" alt="Screenshot 2022-06-28 at 16 33 41" src="https://user-images.githubusercontent.com/9029009/176220494-a96eabe5-8299-4aaf-ba93-d59e8cbfe742.png"> | [Recent events](https://sentry.io/organizations/govuk/issues/3370528976/events/?project=6370326&query=cucumber.scenario%3A%22Check+the+frontend+can+talk+to+Licensing%22&statsPeriod=14d) |

It's possible a data sync process is starting earlier for licensing than [the 10PM we expect for other apps](https://github.com/alphagov/govuk-puppet/blob/32c1bbbb10067078c1406170666a135b4a10aaea/modules/govuk/lib/puppet/parser/functions/data_sync_times.rb#L6). While we may not care much about these environments after working hours, if we decide to filter issues out during this time we should at least understand what is causing them first; it's unclear how to do this without affecting all other Sentry issues. Another option, given how tangential licensing is to GOV.UK, would be to limit these scenarios to only run in Production.

**Comment by ChrisBAshton** [comment]
Since https://github.com/alphagov/govuk-puppet/pull/11954, we no longer have the Smokey Loop, instead using Jenkins cron scheduler to run Smokey every ten minutes.

We've configured Jenkins to only [run the tests between 7am and 7pm](https://github.com/alphagov/govuk-puppet/pull/11954/files#diff-1d6545debf57c939cf04cd386bebe4998adce5de5bff6a55a46e4047e3ef6cbcR24), so this issue should no longer appear. Closing.
