### ISSUE TITLE
Smokey Loop deployments only happen once a day

### ISSUE THREAD

**Issue by benthorner** [alphagov/smokey#961]
Smokey is "deployed" in two forms:

- Smokey Jenkins job (uses the latest commit on `main`)
- Smokey Loop (deployed once a day)

Even though we have [instructions](https://github.com/alphagov/smokey/blob/main/docs/deployment.md#after-you-merge) for it, it's still easy for a developer to forget to deploy Smokey Loop in each environment after merging a change. This can lead to unnecessary or prolonged errors and alerts:

- If the change was meant to fix something, we won't see the benefit until the next day.
- If the change was a preemptive fix for an upcoming change to an app, we won't see the benefit until the next day.

Potential solutions:

- Emphasise the deployment guidance in the PR template. This is unlikely to help as PR templates are easy to ignore.
- Automatically run Smokey_Deploy when a change is merged. This has a slight downside that a faulty change would impact Production straight away. Smokey isn't critical software, though, so agility is probably more important here.

**Comment by ChrisBAshton** [comment]
Card written: https://trello.com/c/JcY1L7so/2710-automatically-run-smokeydeploy-when-a-smokey-change-is-merged
